name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.302
    
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
    - name: Publish Executable
      if: matrix.os == 'windows-latest'
      run: dotnet publish -r win-x64 --configuration Release -p:PublishSingleFile=true -p:PublishTrimmed=true -p:IncludeNativeLibrariesForSelfExtract=true --self-contained true
    - name: Test Executable
      if: matrix.os == 'windows-latest'
      run: ./src/UpDock/bin/Release/net5.0/win-x64/publish/up-dock.exe -e ItsVeryWindy@users.noreply.github.com -s repo:ItsVeryWindy/test-docker-update -d -t ${{ secrets.GITHUB_TOKEN }}
    - name: Test Executable (Git Process)
      if: matrix.os == 'windows-latest'
      run: ./src/UpDock/bin/Release/net5.0/win-x64/publish/up-dock.exe -e ItsVeryWindy@users.noreply.github.com -s repo:ItsVeryWindy/test-docker-update -d -g -t ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Executable
      if: matrix.os == 'ubuntu-latest'
      run: dotnet publish -r linux-x64 --configuration Release -p:PublishSingleFile=true -p:PublishTrimmed=true -p:IncludeNativeLibrariesForSelfExtract=true --self-contained true
    - name: Test Executable
      if: matrix.os == 'ubuntu-latest'
      run: ./src/UpDock/bin/Release/net5.0/linux-x64/publish/up-dock -e ItsVeryWindy@users.noreply.github.com -s repo:ItsVeryWindy/test-docker-update -d -t ${{ secrets.GITHUB_TOKEN }}
    - name: Test Executable (Git Process)
      if: matrix.os == 'ubuntu-latest'
      run: ./src/UpDock/bin/Release/net5.0/linux-x64/publish/up-dock -e ItsVeryWindy@users.noreply.github.com -s repo:ItsVeryWindy/test-docker-update -d -g -t ${{ secrets.GITHUB_TOKEN }}

